### ISSUE TITLE
选择视频，当手机没有视频时会闪退

### ISSUE THREAD

**Issue by gitJusth** [Lichenwei-Dev/ImagePicker#2]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.lcw.library.imagepicker.activity.ImagePickerActivity$a$1.run(ImagePickerActivity.java:322)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6379)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by Lichenwei-Dev** [comment]
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.get(ArrayList.java:411)
> at com.lcw.library.imagepicker.activity.ImagePickerActivity$a$1.run(ImagePickerActivity.java:322)
> at android.os.Handler.handleCallback(Handler.java:754)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:163)
> at android.app.ActivityThread.main(ActivityThread.java:6379)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
> at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

确实存在这个问题，感谢你的反馈，目前已修复，更新最新版本即可。
gradle：implementation 'com.lcw.library:imagepicker:2.1.1'
